version: '3.2'
services:
  database:
    image: mysql
    container_name: blog_db
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --lower_case_table_names=1
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
      - TZ=Europe/Prague
    ports:
      - 127.0.0.1:3306:3306
    networks:
      - blog_net
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10
    volumes:
      - ./data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: blog_phpmyadmin
    depends_on:
      - database
    ports:
      - 127.0.0.1:8082:80
    networks:
      - blog_net
    environment:
      - PMA_HOST=blog_db
      - PMA_USER=root
      - PMA_PASSWORD=$DB_ROOT_PASSWORD
      - TZ=Europe/Prague
networks:
  blog_net:
    driver: bridge

